---
{{- $serviceName := include "rpc.fullname" .  -}}
{{- if .Values.service.name -}}
{{- $serviceName = .Values.service.name -}}
{{- end -}}
{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{ end }}
  labels:
    lavanet.xyz/node_moniker:  {{ include "rpc.moniker"  . }}
    lavanet.xyz/node_type: "rpc"
    {{- include "rpc.labels" . | nindent 4 }}
spec:
  type:  {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{ else }}
  ports:
  {{- range .Value.ports }}
    - name: {{ .name }}
      port: {{ .number }}
      protocol: {{ .protocol }}
      targetPort: {{ .name }}
  {{- end }}
  selector:
    lavanet.xyz/node_moniker:  {{ include "rpc.moniker"  . }}
    lavanet.xyz/node_type: "rpc"
    {{- include "rpc.selectorLabels" . | nindent 4 }}
{{- end }}