---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rpc.fullname"  . }}
  labels:
    lavanet.xyz/node_moniker:  {{ include "rpc.moniker"  . }}
    lavanet.xyz/node_type: "rpc"
    {{- include "rpc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      lavanet.xyz/node_moniker:  {{ include "rpc.moniker"  . }}
      lavanet.xyz/node_type: "rpc"
      {{- include "rpc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        lavanet.xyz/node_moniker:  {{ include "rpc.moniker"  . }}
        lavanet.xyz/node_type: "rpc"
        {{- include "rpc.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "rpc.fullname"  . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          {{- range .Values.extraSecretMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
          {{- range .Values.extraConfigMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
              readOnly: {{ .readOnly }}
          {{- end }}
            - name: {{ include "rpc.fullname"  . }}-data-volume-pvc
              mountPath: {{ .Values.persistentVolume.mountPath }}
              subPath: "{{ .Values.persistentVolume.subPath }}"
          {{- with .Values.envFrom }}
          envFrom: 
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env: 
            - name: DATA_DIR
              value: {{ .Values.persistentVolume.mountPath }} 
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          {{- range .Values.ports }}
            - name: {{ .name }}
              containerPort: {{ .number }}
              protocol: {{ .protocol }}
          {{- end }}
          {{- if .Values.command }}
          {{- with .Values.commmand.name }}
          command: 
            - {{ . | quote }}
          {{- end }}
          {{- with .Values.commmand.args }}
          args:
            {{- toYaml . | nindent 12 -}}
          {{- end }}
          # default command
          {{- else }}
          command: ["run"]
          args: [ ]
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{ if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (unset .Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{ if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (unset .Values.readinessProbe "enabled") | nindent 12 }}
          {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumeClaimTemplates:
        - metadata:
            name:  {{ include "rpc.fullname"  . }}-data-volume-pvc
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 100Gi
      volumes:
        {{- range .Values.extraSecretMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
            {{- with .optional }}
            optional: {{ . }}
            {{- end }}
        {{- end }}
        {{- range .Values.extraConfigMounts }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secretName }}
            {{- with .optional }}
            optional: {{ . }}
            {{- end }}
        {{- end }}