# set the log level for the node
logLevel: "warn"

# override the fullname
fullnameOverride: null
nameOverride: null

# rpc node moniker, will default to the fullname
moniker: null

# chain id of lava
chainId: "lava-testnet-2"

# setup ingress for the node
# example:
# ingress:
#  enabled: true
#  tls:
#    - secretName: lava-rpc-tls
#      hosts:
#        - lava-rpc.example.com
#  rules:
#    - host: lava-rpc.example.com
#      http:
#        paths:
#          - path: /
#            backend:
#              serviceName: lava-rpc
#              servicePort: 5000
#  annotations: {}
ingress:
  enabled: true
  className: "nginx"
  tls: []
  rules: []
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"

# add custom environment variables to the node using secret of configs
envFrom: []

# add custom environment variables to the node
env: []

# image to deploy
image:
  repository: us-central1-docker.pkg.dev/lavanet-public/images/lavad
  pullPolicy: IfNotPresent
  tag: latest

# port to expose the node on
port:
  name: default
  number: 2224
  protocol: TCP

# set service account name
serviceAccountName: null

# service settings
service:
  enabled: true
  name: null
  type: ClusterIP
  annotations: {}
  # override .Values.port with these values
  ports: null

# mount secrets as files, useful for mounting key file
extraSecretMounts: []
  # - name: node-private-key
  #   mountPath: /data
  #   subPath: /keychain/node-private-key
  #   secretName: node-private-key
  #   readOnly: true

# mount config as files, useful for mounting the config file
extraConfigMounts: []
  # - name: node-config
  #   mountPath: /data
  #   subPath: /data/node-config.toml
  #   configName: node-config
  #   readOnly: true

# setup pvc for the node
persistentVolume:
  ## If true, will create/use a Persistent Volume Claim
  ## If false, use emptyDir
  enabled: true

  ## Must match those of existing PV or dynamic provisioner
  ## Ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  accessModes:
    - ReadWriteOnce

  ## Persistent Volume labels
  labels: {}

  ## Persistent Volume annotations
  annotations: {}

  ## Persistent Volume existing claim name
  ## Requires persistentVolume.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  existingClaim: ""

  ## server data Persistent Volume mount root path
  mountPath: /data

  ## data Persistent Volume size
  size: 10Gi

  ## Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  storageClass: null

  ## Subdirectory of data Persistent Volume to mount
  ## Useful if the volume's root directory is not empty
  subPath: ""

  ## Persistent Volume Claim Selector
  ## Useful if Persistent Volumes have been provisioned in advance
  ## Ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector
  selector: null
  ## ex: 
  # selector:
  #  matchLabels:
  #    release: "stable"
  #  matchExpressions:
  #    - { key: environment, operator: In, values: [ dev ] }

  ## Persistent Volume Name
  ## Useful if Persistent Volumes have been provisioned in advance and you want to use a specific one
  ##
  volumeName: null
  # volumeName: ""

  volumeBindingMode: null

  emptyDir:
    ## emptyDir volume size limit
    sizeLimit: ""

# resource limits for the node
resources:
  requests:
    cpu: "250m"
    memory: 250Mi
  limits:
    memory: "2Gi"

# override the start command to start the rpc
command: null

# use a custom readiness probe
readinessProbe:
  enabled: false
  # httpGet:
  #   path: /health
  #   port: 5000
  # initialDelaySeconds: 30
  # periodSeconds: 10
  # timeoutSeconds: 5
  # successThreshold: 1
  # failureThreshold: 3

# use a custom liveness probe
livenessProbe:
  enabled: false
  # httpGet:
  #   path: /health
  #   port: 5000
  # initialDelaySeconds: 30
  # periodSeconds: 10
  # timeoutSeconds: 5
  # successThreshold: 1
  # failureThreshold: 3

imagePullSecrets: []
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
