{{- if .Values.configYaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "provider.fullname" . }}-config-from-values
data:
  provider_config.yaml: |
{{ .Values.configYaml  | indent 4 }}
{{- end -}}