# set the log level for the node
logLevel: "warn"

# provider node moniker, will default to the fullname
moniker: "my-node"

# the url for a lava RPC node
rpcNodeUrl: "https://public-rpc-testnet2.lavanet.xyz:443"

# information about the private key to use for the node
key:
  name: "my-node-key"
  # name of the secret in secret.example.yaml
  secretName: provider-key-secret
  secretKey: key.txt
  passwordSecretName: provider-key-secret
  passwordSecretKey: password

# the url where your provider can be reached
endpoint: "myprovider-provider-helm-test.mydomain.xyz"

# which chain ids your provider will support
supportedChainIds: 
  - LAV1

# setup ingress for your provider
ingress:
  enabled: true
  className: "nginx"
  tls:
    - hosts:
        - myprovider-provider-helm-test.mydomain.xyz
      secretName: mydomain-xyz-tls
  rules:
    - host: myprovider-provider-helm-test.mydomain.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  '{{- include "provider.fullname" . }}'
                port:
                  name: "{{ .Values.port.name }}"
  annotations:
    external-dns.alpha.kubernetes.io/aws-region: us-east-1
    external-dns.alpha.kubernetes.io/set-identifier: my-cluster-name
    external-dns.custom.kubernetes.io/public-load-balancer: 'true'

# configuration for the provider
configYaml: |
  endpoints:
    - api-interface: tendermintrpc
      chain-id: LAV1
      network-address:
        address: 0.0.0.0:2224
        disable-tls: true
      node-urls:
        - url: https://public-rpc-testnet2.lavanet.xyz:443
        - url: https://public-rpc-testnet2.lavanet.xyz:443
    - api-interface: rest
      chain-id: LAV1
      network-address:
        address: 0.0.0.0:2224
        disable-tls: true
      node-urls: 
        url: https://public-rpc-testnet2.lavanet.xyz:443/rest
    - api-interface: grpc
      chain-id: LAV1
      network-address:
        address: 0.0.0.0:2224
        disable-tls: true
      node-urls: 
        url: public-rpc-testnet2.lavanet.xyz:9090