{{- if .Values.configYaml -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consumer.fullname" . }}-config-from-values
data:
  consumer_config.yaml: |
{{ .Values.configYaml  | indent 4 }}
{{- end -}}
